site_name: Visual Place Learning

theme:
  name: readthedocs

nav:
  - Home: index.md

  - Hardware:
      - Peltier Plates: hardware/peltier_plates.md
      - LED Display: hardware/led_display.md
      - ESP32: hardware/esp32.md
      - Raspberry Pi: hardware/raspberry_pi.md
      - IR LED Lights: hardware/ir_led_lights.md
      - Monochrome Camera: hardware/monochrome_camera.md
      
  - Software:
      - Remote Web Server: software/remote_web_server.md
      - Behavioural Tracking: software/Behavioural_tracking.md
      - 3D CAD Designs: software/3d_CAD.md
